// Auto-generated by the financial-advisor skill.
// Do not edit by hand — regenerate from data/*.json instead.
window.DATA = {
  generated_at: "2026-04-16",
  profile: {
    name: "Minh",
    base_currency: "AUD",
    income_aud: 4900,
    pay_day: 15,
    risk: "moderate",
    horizon: "long-term (years)",
    experience: "new investor"
  },
  net_worth_aud: 1300,
  savings: {
    current_aud: 1300,
    target_aud: 9600,
    progress_percent: 14
  },
  current_month: {
    month: "2026-04",
    income_aud: 4900,
    spending_aud: 3200,
    savings_aud: 1200,
    investments_aud: 500,
    investment_split: { AU: 500, VN: 0, US: 0 },
    status: "Pending Macquarie Compliance approval. April all-AU via Pearler (TCBS not yet live)."
  },
  portfolio: {
    total_invested_aud: 0,
    holdings: []
  },
  watchlist: [
    { ticker: "VAS", market: "ASX", type: "ETF", risk: "low", price: "A$110.85", rating: "BUY", thesis: "ASX 300 core. 3.08% yield (partial franking). 2.95% below 52w high. Fair value." },
    { ticker: "VGS", market: "ASX", type: "ETF", risk: "low/med", price: "A$146.80", rating: "BUY", thesis: "Upgraded HOLD->BUY. 6% below 52w high. Distribution 20 Apr. AUD tailwind." },
    { ticker: "IVV", market: "ASX", type: "ETF", risk: "low/med", price: "A$65.07", rating: "BUY (small)", thesis: "S&P 500 at record 7,022. Forward P/E 22-23x — premium. Size small." },
    { ticker: "FPT", market: "HOSE", type: "stock", risk: "medium", price: "95,400 VND", rating: "STRONG BUY (pending broker)", thesis: "Down 30% from 52w high while VN-Index at record. 24% below analyst target. P/E 15.2x fwd. Revenue +19%, earnings +22%." },
    { ticker: "VNM", market: "HOSE", type: "stock", risk: "red flag", price: "60,900 VND", rating: "WAIT — RED FLAG", thesis: "8% yield BUT payout ratio 130% — dividend not covered by earnings. Unsustainable. Do not buy on yield alone." },
    { ticker: "HPG", market: "HOSE", type: "stock", risk: "med/high", price: "28,050 VND", rating: "WATCH", thesis: "NEW. Steel giant, no dividend. 2024 earnings +74%. 25% upside to 35,013 target. Diversifier to FPT in VN sleeve." }
  ],
  fx_rates: {
    AUD_USD: 0.7169,
    AUD_VND: 18864,
    USD_VND: 26310,
    last_updated: "2026-04-16"
  },
  setup_checklist: [
    { task: "Sign up for AU broker (Pearler recommended)", done: false },
    { task: "Sign up for VN broker (TCBS recommended)", done: false },
    { task: "Macquarie Compliance approval for personal trading", done: false },
    { task: "Configure 8 AM Sydney daily research cron", done: true },
    { task: "First investment executed", done: false },
    { task: "Emergency fund at $9,600 AUD", done: false }
  ],
  latest_research: {
    date: "2026-04-16",
    file: "research/2026-04-16.md",
    summary: "US + VN at records, AU mixed. AUD strengthened 4% vs USD/VND. April $500 all-AU proposed split: VAS $250 / VGS $150 / IVV $100. FPT at 30% discount to 52w high — top VN pick for May. VNM red-flagged: 130% payout ratio unsustainable."
  }
};
