// Auto-generated by the financial-advisor skill.
// Do not edit by hand — regenerate from data/*.json instead.
window.DATA = {
  generated_at: "2026-04-12T08:00:00+10:00",
  profile: {
    name: "Minh",
    base_currency: "AUD",
    income_aud: 4900,
    pay_day: 15,
    risk: "moderate",
    horizon: "long-term (years)",
    experience: "new investor"
  },
  net_worth_aud: 1300,
  savings: {
    current_aud: 1300,
    target_aud: 9600,
    progress_percent: 14
  },
  current_month: {
    month: "2026-04",
    income_aud: 4900,
    spending_aud: 3200,
    savings_aud: 1700,
    investments_aud: 0,
    investment_split: { AU: 0, VN: 0, US: 0 },
    status: "Deferred — April trades on hold pending Macquarie Compliance approval. First invest month = May."
  },
  portfolio: {
    total_invested_aud: 0,
    holdings: []
  },
  watchlist: [
    { ticker: "VAS", market: "ASX", type: "ETF", risk: "low", price: "A$110.85", rating: "BUY (May)", thesis: "Core AU ETF. 3.08% yield (partial franking). ~3% off 52w high — not overheated. Target entry ≤ A$112." },
    { ticker: "VGS", market: "ASX", type: "ETF", risk: "low/med", price: "A$145.75", rating: "BUY (May)", thesis: "Global developed ex-AU. 2.47% yield. ~7% off 52w high = healthy pullback. Target entry ≤ A$150." },
    { ticker: "IVV", market: "ASX", type: "ETF", risk: "low/med", price: "A$63.25", rating: "BUY (May)", thesis: "S&P 500 on ASX. S&P −4% YTD = accumulation entry. 0.04% fee. Target entry ≤ A$65." },
    { ticker: "FPT", market: "HOSE", type: "stock", risk: "medium", price: "81,600 VND", rating: "BUY (pending TCBS)", thesis: "VN tech leader. P/E ~20x justified by 18-20% revenue growth. 2.37% yield, sustainable ~30% payout. At target." },
    { ticker: "VNM", market: "HOSE", type: "stock", risk: "med/high", price: "60,900 VND", rating: "FLAGGED — DO NOT BUY", thesis: "Yield 7.98% BUT payout ratio 130% — dividend unsustainable without earnings recovery. Reassess after FY26 results." }
  ],
  fx_rates: {
    AUD_USD: 0.7062,
    AUD_VND: 18613,
    USD_VND: 26326,
    last_updated: "2026-04-12T08:00:00+10:00"
  },
  setup_checklist: [
    { task: "Sign up for AU broker (Pearler recommended)", done: false },
    { task: "Sign up for VN broker (TCBS recommended)", done: false },
    { task: "Macquarie Compliance approval for personal trading", done: false },
    { task: "Configure 8 AM Sydney daily research cron", done: true },
    { task: "First investment executed", done: false },
    { task: "Emergency fund at $9,600 AUD", done: false }
  ],
  latest_research: {
    date: "2026-04-12",
    file: "research/2026-04-12.md",
    summary: "Weekend brief. ASX 200 +4% best week since Oct 2022. VN-Index +43% YoY (hot, FTSE EM reclass Sept). S&P −4% YTD = accumulation entry. VAS/VGS/IVV ready for May. FPT at entry target, pending TCBS. VNM FLAGGED — 130% payout ratio, yield trap risk. April trades deferred — Macquarie Compliance approval needed."
  }
};
