// Auto-generated by the financial-advisor skill.
// Do not edit by hand — regenerate from data/*.json instead.
window.DATA = {
  generated_at: "2026-04-15",
  profile: {
    name: "Minh",
    base_currency: "AUD",
    income_aud: 4900,
    pay_day: 15,
    risk: "moderate",
    horizon: "long-term (years)",
    experience: "new investor"
  },
  net_worth_aud: 1300,
  savings: {
    current_aud: 1300,
    target_aud: 9600,
    progress_percent: 14
  },
  current_month: {
    month: "2026-04",
    income_aud: 4900,
    spending_aud: 3200,
    savings_aud: 1200,
    investments_aud: 500,
    investment_split: { AU: 500, VN: 0, US: 0 },
    status: "Payday today — $500 to AU (Pearler) if Compliance approved; else carry to May"
  },
  portfolio: {
    total_invested_aud: 0,
    holdings: []
  },
  watchlist: [
    { ticker: "VAS", market: "ASX", type: "ETF", risk: "low", price: "$110.85", rating: "BUY", thesis: "Core AU ETF — broad ASX 300 exposure, 3.08% yield, 68% franked, -2.9% from 52w high" },
    { ticker: "IVV", market: "ASX", type: "ETF", risk: "low/med", price: "$65.10", rating: "BUY (small)", thesis: "S&P 500 via ASX — S&P near 7,000, -7.1% from 52w high, fwd P/E ~21.5x" },
    { ticker: "VGS", market: "ASX", type: "ETF", risk: "low/med", price: "$146.80", rating: "HOLD", thesis: "Global ex-AU — 60% overlap with IVV. Add when budget grows past $1k/month" },
    { ticker: "CSL", market: "ASX", type: "stock", risk: "medium", price: "$140.58", rating: "WATCH", thesis: "Blue chip biotech, -50% below consensus target, BUT H1 2026 NPAT -81% YoY. Wait for stabilisation" },
    { ticker: "FPT", market: "HOSE", type: "stock", risk: "medium", price: "95,400 VND", rating: "WATCH", thesis: "VN tech leader, rallied 17% in a week, P/E ~19x. VN market overheated at index level" },
    { ticker: "VNM", market: "HOSE", type: "stock", risk: "low/med", price: "62,800 VND", rating: "WAIT", thesis: "Vinamilk — 8% yield, 130% payout ratio unsustainable. Wait for 24 Apr earnings" }
  ],
  fx_rates: {
    AUD_USD: 0.7137,
    AUD_VND: 18612,
    USD_VND: 26078,
    last_updated: "2026-04-15"
  },
  market_flags: [
    { market: "VN-Index", status: "overheated", note: "+44% YoY with foreign outflows. Drip-feed VN exposure once TCBS is live." }
  ],
  setup_checklist: [
    { task: "Sign up for AU broker (Pearler recommended)", done: false },
    { task: "Sign up for VN broker (TCBS recommended)", done: false },
    { task: "Configure 8 AM Sydney daily research cron", done: true },
    { task: "First investment executed", done: false },
    { task: "Emergency fund at $9,600 AUD", done: false }
  ],
  latest_research: {
    date: "2026-04-15",
    file: "research/2026-04-15.md",
    summary: "Payday. $500 allocated AU-only (70% VAS / 30% IVV) pending Compliance approval. VN market flagged overheated (+44% YoY, foreign outflows). CSL added to watchlist with caution after -81% H1 NPAT drop. AUD strengthened to 0.7137 against USD (+3.6%)."
  }
};
